# Nixpacks 配置 - 前端静态服务

[phases.setup]
nixPkgs = ["nodejs_22", "caddy"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "caddy run --config Caddyfile --adapter caddyfile"
