# Nixpacks 配置 - 前端静态服务

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["rm -rf node_modules/.cache || true", "npm ci --cache /tmp/.npm"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"
