// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv-flow
import dotenvFlow from "dotenv-flow";
dotenvFlow.config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
